version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --workers 4  
    ports:
      - "5000:5000"
    environment:
      - ENV=production
    volumes:
      - .:/app
