on:
  schedule:
    - cron: '0 16 * * *'
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python Script
      run: python today_Agri_weather.py
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Commit and push changes
      run: |
        git config --global user.name "danuni29"
        git config --global user.email "hekdms@jbnu.ac.kr"
        if [ "$(git status --porcelain ./Agri_Weather/*.csv)" ]; then
          git add ./Agri_Weather/*.csv
          git commit -m "Update Weather Data - $(TZ='Asia/Seoul' date +'%Y-%m-%d')"
          git push https://danuni29:${{ secrets.MY_GITHUB_TOKEN }}@github.com/danuni29/Agri-Weather-DB.git
        else
          echo "No changes to commit."
        fi
